/** @typedef {import("./types.d.ts").ProfileConfig} ProfileConfig */

/**
 * @param {string[]} items
 */
function formatInlineList(items) {
  return items.join(" · ");
}

/**
 * @param {ProfileConfig} config
 */
function renderHeader(config) {
  const { name, title, headline, summary, company, location, links, email } = config;

  return `# ${name}

**${title}** — ${headline}

${summary}

Currently at **[${company.name}](${company.url})** · ${location}

[![Portfolio](https://img.shields.io/badge/Portfolio-abd1bayev.uz-667eea?style=flat-square&logo=google-chrome&logoColor=white)](${links.portfolio})
[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=flat-square&logo=linkedin&logoColor=white)](${links.linkedin})
[![Telegram](https://img.shields.io/badge/Telegram-@abd1bayev-26A5E4?style=flat-square&logo=telegram&logoColor=white)](${links.telegram})
[![Email](https://img.shields.io/badge/Email-Contact-EA4335?style=flat-square&logo=gmail&logoColor=white)](mailto:${email})`;
}

/**
 * @param {ProfileConfig} config
 */
function renderAbout(config) {
  const { bios } = config;

  return `## About

<details open>
<summary><b>English</b></summary>
<br/>

${bios.en}

</details>

<details>
<summary><b>O'zbek</b></summary>
<br/>

${bios.uz}

</details>

<details>
<summary><b>Русский</b></summary>
<br/>

${bios.ru}

</details>`;
}

/**
 * @param {ProfileConfig} config
 */
function renderFocusAreas(config) {
  const rows = config.focusAreas
    .map(
      (area) =>
        `| **${area.domain}** | ${area.description} | ${formatInlineList(area.technologies)} |`,
    )
    .join("\n");

  return `## Focus Areas

| Domain | Scope | Stack |
|:-------|:------|:------|
${rows}`;
}

/**
 * @param {ProfileConfig} config
 */
function renderPrinciples(config) {
  const items = config.principles.map((p) => `- ${p}`).join("\n");
  return `## Engineering Principles

${items}`;
}

/**
 * @param {ProfileConfig} config
 */
function renderTechStack(config) {
  const { techStack } = config;

  return `## Tech Stack

| Layer | Technologies |
|:------|:-------------|
| **Languages** | ${formatInlineList(techStack.languages)} |
| **Backend** | ${formatInlineList(techStack.backend)} |
| **Data** | ${formatInlineList(techStack.data)} |
| **Infrastructure** | ${formatInlineList(techStack.infrastructure)} |
| **Frontend** | ${formatInlineList(techStack.frontend)} |

<img src="https://skillicons.dev/icons?i=python,django,fastapi,postgres,redis,docker,git,linux&perline=8" alt="Core technologies" />`;
}

/**
 * @param {ProfileConfig} config
 */
function renderWriting(config) {
  const rows = config.articles
    .map((a) => `| [${a.title}](${a.url}) | ${a.topic} |`)
    .join("\n");

  return `## Writing

| Article | Topic |
|:--------|:------|
${rows}`;
}

/**
 * @param {ProfileConfig} config
 */
function renderActivity(config) {
  const { username, theme } = config;

  return `## GitHub Activity

<img src="https://github-readme-activity-graph.vercel.app/graph?username=${username}&theme=react-dark&hide_border=true&bg_color=0d1117&color=${theme.accent}&line=${theme.accent}&point=${theme.accent}&area=true&custom_title=Contribution%20Activity" width="100%" alt="Contribution activity" />

<br />

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="./assets/github-contribution-grid-snake-dark.svg"/>
  <source media="(prefers-color-scheme: light)" srcset="./assets/github-contribution-grid-snake.svg"/>
  <img src="./assets/github-contribution-grid-snake.svg" alt="Contribution snake" width="100%"/>
</picture>`;
}

/**
 * @param {ProfileConfig} config
 */
function renderContact(config) {
  const { name, links, email } = config;

  return `## Contact

Open to technical discussions, collaboration, and backend/data engineering opportunities.

| | |
|:--|:--|
| **Portfolio** | [abd1bayev.uz](${links.portfolio}) |
| **Website** | [abd1bayev.vercel.app](${links.website}) |
| **LinkedIn** | [linkedin.com/in/jasur-abdibayev](${links.linkedin}) |
| **Medium** | [medium.com/@jasurabdibayev0](${links.medium}) |
| **Telegram** | [@abd1bayev](${links.telegram}) |
| **Email** | [${email}](mailto:${email}) |

---

<sub>Profile README generated from <code>config/profile.json</code> · ${name}</sub>`;
}

/**
 * @param {ProfileConfig} config
 * @returns {string}
 */
export function renderReadme(config) {
  return [
    "<!-- Generated by scripts/generate-readme.mjs — edit config/profile.json -->",
    renderHeader(config),
    "",
    "---",
    "",
    renderAbout(config),
    "",
    "---",
    "",
    renderFocusAreas(config),
    "",
    "---",
    "",
    renderPrinciples(config),
    "",
    "---",
    "",
    renderTechStack(config),
    "",
    "---",
    "",
    renderWriting(config),
    "",
    "---",
    "",
    renderActivity(config),
    "",
    "---",
    "",
    renderContact(config),
    "",
  ].join("\n");
}
